receivers:
  monitoringjobs:
    jobs:
      - name: test
        schedule:
          interval: 3
        exec:
          command: sh
          arguments:
            - -c
            - "echo 'THIS IS FINE! | percent_packet_loss=0'"
        output:
          metrics:
            transformer: nagios_perfdata

exporters:
  logging:
    logLevel: debug

service:
  pipelines:
    metrics:
      receivers: [monitoringjobs]
      exporters: [logging]
    logs:
      receivers: [monitoringjobs]
      exporters: [logging]
