receivers:
  monitoringjobs:
    jobs:
      - name: test
        schedule:
          interval: 3
        exec:
          command: sh
          arguments:
            - -c
            - "echo foobar"

exporters:
  logging:
    logLevel: debug

service:
  pipelines:
    metrics:
      receivers: [monitoringjobs]
      exporters: [logging]
    logs:
      receivers: [monitoringjobs]
      exporters: [logging]
