receivers:
  monitoringjobs:
    jobs:
      - name: test
        schedule:
          interval: 10

exporters:
  logging:
    logLevel: debug

service:
  pipelines:
    metrics:
      receivers: [monitoringjobs]
      exporters: [logging]
    logs:
      receivers: [monitoringjobs]
      exporters: [logging]
