name: Test

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Test
        run: echo ::notice title=TestTitle::TestMessage
